### ISSUE TITLE
Error running sample scripts on Python 3.7.2 (64-bit)

### ISSUE THREAD

**Issue by billerl** [0xJeremy/socket.engine#1]
Error when running server

> line 9, in <module>
>     if data is not none:
> NameError: name 'none' is not defined

to run I had to change 
`if data is not none:`
to
`if data is not None:`

Error when running Client:

>  line 1, in <module>
>     from socketengine import CLIENT
> ImportError: cannot import name 'CLIENT' from 'socketengine'

`from socketengine import CLIENT`
to run I had to change import:
`from socketengine import client `

**Comment by 0xJeremy** [comment]
Both good catches! I had fixed the `none` issue on a local branch but hadn't pushed. Both issues not resolved. Thanks!
